// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BalanceAfterRealLevelPayments
int BalanceAfterRealLevelPayments(int nominal_payment, int n, int balance, double r_earnings, double cpi, bool inArrears);
RcppExport SEXP CRIMpp_BalanceAfterRealLevelPayments(SEXP nominal_paymentSEXP, SEXP nSEXP, SEXP balanceSEXP, SEXP r_earningsSEXP, SEXP cpiSEXP, SEXP inArrearsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nominal_payment(nominal_paymentSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type balance(balanceSEXP);
    Rcpp::traits::input_parameter< double >::type r_earnings(r_earningsSEXP);
    Rcpp::traits::input_parameter< double >::type cpi(cpiSEXP);
    Rcpp::traits::input_parameter< bool >::type inArrears(inArrearsSEXP);
    rcpp_result_gen = Rcpp::wrap(BalanceAfterRealLevelPayments(nominal_payment, n, balance, r_earnings, cpi, inArrears));
    return rcpp_result_gen;
END_RCPP
}
// RealPensionLevel
int RealPensionLevel(int n, int balance, double r_earnings, double cpi, bool inArrears);
RcppExport SEXP CRIMpp_RealPensionLevel(SEXP nSEXP, SEXP balanceSEXP, SEXP r_earningsSEXP, SEXP cpiSEXP, SEXP inArrearsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type balance(balanceSEXP);
    Rcpp::traits::input_parameter< double >::type r_earnings(r_earningsSEXP);
    Rcpp::traits::input_parameter< double >::type cpi(cpiSEXP);
    Rcpp::traits::input_parameter< bool >::type inArrears(inArrearsSEXP);
    rcpp_result_gen = Rcpp::wrap(RealPensionLevel(n, balance, r_earnings, cpi, inArrears));
    return rcpp_result_gen;
END_RCPP
}
