# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Balance after n real level payments
#' @name BalanceAfterRealLevelPayments
#' @description Super balance after level payments.
#' @param nominal_payment An integer representing the payment (in nominal terms with respect to \code{balance}).
#' @param n Number of periods (years).
#' @param balance The super balance prior to retirement.
#' @param r_earnings The rate of earnings growth.
#' @param cpi The rate of CPI growth.
#' @param inArrears (logical) Are the payments made at the end of 12 months (\emph{i.e.} after the balance has grown)?
#' @export
NULL

BalanceAfterRealLevelPayments <- function(nominal_payment, n, balance, r_earnings, cpi, inArrears) {
    .Call('CRIMpp_BalanceAfterRealLevelPayments', PACKAGE = 'CRIMpp', nominal_payment, n, balance, r_earnings, cpi, inArrears)
}

#' @title Real level of pension payments giving starting retirement conditions
#' @name RealPensionLevel
#' @description The value of a cpi-adjusted pension in nominal terms.
#' @param n The number of periods.
#' @param balance The balance at retirement.
#' @param r_earnings The rate of earnings growth (\code{r_earnings = 0.065} means 6.5\%).
#' @param cpi The rate of CPI.
#' @param inArrears Are the payments paid in arrears (\emph{i.e.} before the balance has grown through \code{r_earnings}.)
#' @export
NULL

RealPensionLevel <- function(n, balance, r_earnings, cpi, inArrears) {
    .Call('CRIMpp_RealPensionLevel', PACKAGE = 'CRIMpp', n, balance, r_earnings, cpi, inArrears)
}

