# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Balance after n real level payments
#' @name BalanceAfterRealLevelPayments
#' @description Super balance after level payments.
#' @param nominal_payment An integer representing the payment (in nominal terms with respect to \code{balance}).
#' @param n Number of periods (years).
#' @param balance The super balance prior to retirement.
#' @param r_earnings The rate of earnings growth.
#' @param cpi The rate of CPI growth.
#' @param inArrears (logical) Are the payments made at the end of 12 months (\emph{i.e.} after the balance has grown)?
#' @export
NULL

BalanceAfterRealLevelPayments <- function(nominal_payment, n, balance, r_earnings, cpi, inArrears) {
    .Call('CRIMpp_BalanceAfterRealLevelPayments', PACKAGE = 'CRIMpp', nominal_payment, n, balance, r_earnings, cpi, inArrears)
}

#' @title Real level of pension payments giving starting retirement conditions
#' @name RealPensionLevel
#' @description The value of a cpi-adjusted pension in nominal terms.
#' @param n The number of periods.
#' @param balance The balance at retirement.
#' @param r_earnings The rate of earnings growth (\code{r_earnings = 0.065} means 6.5\%).
#' @param cpi The rate of CPI.
#' @param inArrears Are the payments paid in arrears (\emph{i.e.} before the balance has grown through \code{r_earnings}.)
#' @export
NULL

RealPensionLevel <- function(n, balance, r_earnings, cpi, inArrears) {
    .Call('CRIMpp_RealPensionLevel', PACKAGE = 'CRIMpp', n, balance, r_earnings, cpi, inArrears)
}

#' @title Average income in retirement
#' @name aveRetInc
#' @description Average income in retirement.
#' @param AWOTE_prop Proportion of AWOTE.
#' @export aveRetInc
NULL

showOutput <- function(x) {
    invisible(.Call('CRIMpp_showOutput', PACKAGE = 'CRIMpp', x))
}

aveRetInc <- function(AWOTE_prop = 1L, AWOTE_starting_year = 78200, start_balance = 0, deflator = "CPI", starting_age = 30L, starting_year = 2016L, retirement_age = 70L, death_age = 92L, short_run_wage_index = as.numeric( c(0.0225, 0.0250, 0.0275, 0.0325, 0.0350)), long_run_wage_index = 0.0404, long_term_CPI = 0.0250, contribution_tax = 0.15, asset_earnings_accumulation = 0.0650, earnings_tax_accumulation = 0.15, asset_earnings_pension = 0.0550, earnings_tax_pension = 0.0, taxable_earnings = 0.53) {
    .Call('CRIMpp_aveRetInc', PACKAGE = 'CRIMpp', AWOTE_prop, AWOTE_starting_year, start_balance, deflator, starting_age, starting_year, retirement_age, death_age, short_run_wage_index, long_run_wage_index, long_term_CPI, contribution_tax, asset_earnings_accumulation, earnings_tax_accumulation, asset_earnings_pension, earnings_tax_pension, taxable_earnings)
}

